export const OverSuperList = [
  {
    id: "1",
    image: "images/product/1.png",
    price: "€3,27",
    title: "Draadloze koptelefoon",
    selled: "1000+ verkocht",
    rating: "4.7",
    shipment: "Gratis verzending",
  },
  {
    id: "2",
    image: "images/product/1.png",
    price: "€3,27",
    title: "Draadloze koptelefoon",
    selled: "1000+ verkocht",
    rating: "4.7",
    shipment: "Gratis verzending",
  },
  {
    id: "3",
    image: "images/product/1.png",
    price: "€3,27",
    title: "Draadloze koptelefoon",
    selled: "1000+ verkocht",
    rating: "4.7",
    shipment: "Gratis verzending",
  },
  {
    id: "4",
    image: "images/product/1.png",
    price: "€3,27",
    title: "Draadloze koptelefoon",
    selled: "1000+ verkocht",
    rating: "4.7",
    shipment: "Gratis verzending",
  },
];

export const OverProdList = [
  {
    id: "1",
    image: "images/product/1.png",
    price: "€3,27",
    title: "Draadloze koptelefoon",
    selled: "1000+ verkocht",
    rating: "4.7",
    shipment: "Gratis verzending",
  },
  {
    id: "2",
    image: "images/product/1.png",
    price: "€3,27",
    title: "Draadloze koptelefoon",
    selled: "1000+ verkocht",
    rating: "4.7",
    shipment: "Gratis verzending",
  },
  {
    id: "3",
    image: "images/product/1.png",
    price: "€3,27",
    title: "Draadloze koptelefoon",
    selled: "1000+ verkocht",
    rating: "4.7",
    shipment: "Gratis verzending",
  },
  {
    id: "4",
    image: "images/product/1.png",
    price: "€3,27",
    title: "Draadloze koptelefoon",
    selled: "1000+ verkocht",
    rating: "4.7",
    shipment: "Gratis verzending",
  },
  {
    id: "5",
    image: "images/product/1.png",
    price: "€3,27",
    title: "Draadloze koptelefoon",
    selled: "1000+ verkocht",
    rating: "4.7",
    shipment: "Gratis verzending",
  },
  {
    id: "6",
    image: "images/product/1.png",
    price: "€3,27",
    title: "Draadloze koptelefoon",
    selled: "1000+ verkocht",
    rating: "4.7",
    shipment: "Gratis verzending",
  },
  {
    id: "7",
    image: "images/product/1.png",
    price: "€3,27",
    title: "Draadloze koptelefoon",
    selled: "1000+ verkocht",
    rating: "4.7",
    shipment: "Gratis verzending",
  },
  {
    id: "8",
    image: "images/product/1.png",
    price: "€3,27",
    title: "Draadloze koptelefoon",
    selled: "1000+ verkocht",
    rating: "4.7",
    shipment: "Gratis verzending",
  },
];
